/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mainwindow (void)
{
  GtkWidget *mainwindow;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *new1;
  GtkWidget *save1;
  GtkWidget *delete2;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit1;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *about1;
  GtkWidget *addresscombobox;
  GtkWidget *hseparator2;
  GtkWidget *hbox1;
  GtkWidget *buddy_button;
  GtkWidget *buddy;
  GtkWidget *fixed1;
  GtkWidget *lastnameentry;
  GtkWidget *firstnameentry;
  GtkWidget *label2;
  GtkWidget *streetentry;
  GtkWidget *label4;
  GtkWidget *noentry;
  GtkWidget *label5;
  GtkWidget *zipentry;
  GtkWidget *cityentry;
  GtkWidget *label7;
  GtkWidget *phoneentry;
  GtkWidget *label8;
  GtkWidget *mobileentry;
  GtkWidget *label9;
  GtkWidget *emailentry;
  GtkWidget *label10;
  GtkWidget *emailsend;
  GtkWidget *label6;
  GtkWidget *label3;
  GtkWidget *url;
  GtkWidget *hseparator1;
  GtkWidget *hbuttonbox1;
  GtkWidget *newbutton;
  GtkWidget *savebutton;
  GtkWidget *deletebutton;
  GtkWidget *quitbutton;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  mainwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (mainwindow, 611, 274);
  gtk_window_set_title (GTK_WINDOW (mainwindow), "gfa");
  gtk_window_set_resizable (GTK_WINDOW (mainwindow), FALSE);
  gtk_window_set_icon_name (GTK_WINDOW (mainwindow), "stock_book_red");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (mainwindow), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic ("_Contact");
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  new1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (new1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), new1);

  save1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), save1);

  delete2 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_show (delete2);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), delete2);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quit1);

  menuitem4 = gtk_menu_item_new_with_mnemonic ("_Help");
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  about1 = gtk_image_menu_item_new_from_stock ("gtk-about", accel_group);
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), about1);

  addresscombobox = gtk_combo_box_new_text ();
  gtk_widget_show (addresscombobox);
  gtk_box_pack_start (GTK_BOX (vbox1), addresscombobox, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (addresscombobox), 3);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator2, FALSE, TRUE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  buddy_button = gtk_button_new ();
  gtk_widget_show (buddy_button);
  gtk_box_pack_start (GTK_BOX (hbox1), buddy_button, FALSE, FALSE, 0);
  gtk_widget_set_size_request (buddy_button, 123, -1);
  gtk_container_set_border_width (GTK_CONTAINER (buddy_button), 3);

  buddy = create_pixmap (mainwindow, "person.png");
  gtk_widget_show (buddy);
  gtk_container_add (GTK_CONTAINER (buddy_button), buddy);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_box_pack_start (GTK_BOX (hbox1), fixed1, TRUE, TRUE, 0);

  lastnameentry = gtk_entry_new ();
  gtk_widget_show (lastnameentry);
  gtk_fixed_put (GTK_FIXED (fixed1), lastnameentry, 80, 16);
  gtk_widget_set_size_request (lastnameentry, 160, 26);

  firstnameentry = gtk_entry_new ();
  gtk_widget_show (firstnameentry);
  gtk_fixed_put (GTK_FIXED (fixed1), firstnameentry, 320, 16);
  gtk_widget_set_size_request (firstnameentry, 160, 26);

  label2 = gtk_label_new ("first name:");
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 240, 16);
  gtk_widget_set_size_request (label2, 88, 24);

  streetentry = gtk_entry_new ();
  gtk_widget_show (streetentry);
  gtk_fixed_put (GTK_FIXED (fixed1), streetentry, 80, 48);
  gtk_widget_set_size_request (streetentry, 288, 26);

  label4 = gtk_label_new ("street:");
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 32, 48);
  gtk_widget_set_size_request (label4, 48, 24);

  noentry = gtk_entry_new ();
  gtk_widget_show (noentry);
  gtk_fixed_put (GTK_FIXED (fixed1), noentry, 408, 48);
  gtk_widget_set_size_request (noentry, 72, 26);

  label5 = gtk_label_new ("no.:");
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 376, 48);
  gtk_widget_set_size_request (label5, 32, 24);

  zipentry = gtk_entry_new ();
  gtk_widget_show (zipentry);
  gtk_fixed_put (GTK_FIXED (fixed1), zipentry, 80, 80);
  gtk_widget_set_size_request (zipentry, 56, 26);

  cityentry = gtk_entry_new ();
  gtk_widget_show (cityentry);
  gtk_fixed_put (GTK_FIXED (fixed1), cityentry, 184, 80);
  gtk_widget_set_size_request (cityentry, 295, 27);

  label7 = gtk_label_new ("city:");
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 144, 80);
  gtk_widget_set_size_request (label7, 40, 24);

  phoneentry = gtk_entry_new ();
  gtk_widget_show (phoneentry);
  gtk_fixed_put (GTK_FIXED (fixed1), phoneentry, 80, 112);
  gtk_widget_set_size_request (phoneentry, 160, 27);

  label8 = gtk_label_new ("phone:");
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 24, 112);
  gtk_widget_set_size_request (label8, 56, 24);

  mobileentry = gtk_entry_new ();
  gtk_widget_show (mobileentry);
  gtk_fixed_put (GTK_FIXED (fixed1), mobileentry, 320, 112);
  gtk_widget_set_size_request (mobileentry, 160, 27);

  label9 = gtk_label_new ("mobile:");
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed1), label9, 264, 112);
  gtk_widget_set_size_request (label9, 56, 24);

  emailentry = gtk_entry_new ();
  gtk_widget_show (emailentry);
  gtk_fixed_put (GTK_FIXED (fixed1), emailentry, 80, 144);
  gtk_widget_set_size_request (emailentry, 332, 27);

  label10 = gtk_label_new ("email:");
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed1), label10, 32, 144);
  gtk_widget_set_size_request (label10, 48, 24);

  emailsend = gtk_button_new_with_mnemonic ("send");
  gtk_widget_show (emailsend);
  gtk_fixed_put (GTK_FIXED (fixed1), emailsend, 416, 144);
  gtk_widget_set_size_request (emailsend, 64, 27);
  gtk_tooltips_set_tip (tooltips, emailsend, "Send an email to your contact with your mail client.", NULL);

  label6 = gtk_label_new ("zip:");
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 40, 80);
  gtk_widget_set_size_request (label6, 48, 24);

  label3 = gtk_label_new ("last name:");
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 8, 16);
  gtk_widget_set_size_request (label3, 72, 24);

  url = gtk_label_new ("label14");
  gtk_fixed_put (GTK_FIXED (fixed1), url, 8, 0);
  gtk_widget_set_size_request (url, 46, 17);
  gtk_widget_set_sensitive (url, FALSE);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator1, FALSE, TRUE, 0);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbuttonbox1, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox1), 3);

  newbutton = gtk_button_new_from_stock ("gtk-new");
  gtk_widget_show (newbutton);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), newbutton);
  GTK_WIDGET_SET_FLAGS (newbutton, GTK_CAN_DEFAULT);

  savebutton = gtk_button_new_from_stock ("gtk-save");
  gtk_widget_show (savebutton);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), savebutton);
  GTK_WIDGET_SET_FLAGS (savebutton, GTK_CAN_DEFAULT);

  deletebutton = gtk_button_new_from_stock ("gtk-delete");
  gtk_widget_show (deletebutton);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), deletebutton);
  GTK_WIDGET_SET_FLAGS (deletebutton, GTK_CAN_DEFAULT);

  quitbutton = gtk_button_new_from_stock ("gtk-quit");
  gtk_widget_show (quitbutton);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), quitbutton);
  GTK_WIDGET_SET_FLAGS (quitbutton, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) mainwindow, "delete_event",
                    G_CALLBACK (on_mainwindow_delete_event),
                    NULL);
  g_signal_connect ((gpointer) mainwindow, "realize",
                    G_CALLBACK (on_mainwindow_realize),
                    NULL);
  g_signal_connect ((gpointer) new1, "activate",
                    G_CALLBACK (on_new_activate),
                    NULL);
  g_signal_connect ((gpointer) save1, "activate",
                    G_CALLBACK (on_save_activate),
                    NULL);
  g_signal_connect ((gpointer) delete2, "activate",
                    G_CALLBACK (on_delete_activate),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about_activate),
                    NULL);
  g_signal_connect ((gpointer) addresscombobox, "changed",
                    G_CALLBACK (on_addresscombobox_changed),
                    NULL);
  g_signal_connect ((gpointer) buddy_button, "clicked",
                    G_CALLBACK (on_buddy_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) emailsend, "clicked",
                    G_CALLBACK (on_emailsend_clicked),
                    NULL);
  g_signal_connect ((gpointer) newbutton, "clicked",
                    G_CALLBACK (on_newbutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) savebutton, "clicked",
                    G_CALLBACK (on_savebutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) deletebutton, "clicked",
                    G_CALLBACK (on_deletebutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) quitbutton, "clicked",
                    G_CALLBACK (on_quitbutton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mainwindow, mainwindow, "mainwindow");
  GLADE_HOOKUP_OBJECT (mainwindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (mainwindow, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (mainwindow, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (mainwindow, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (mainwindow, new1, "new1");
  GLADE_HOOKUP_OBJECT (mainwindow, save1, "save1");
  GLADE_HOOKUP_OBJECT (mainwindow, delete2, "delete2");
  GLADE_HOOKUP_OBJECT (mainwindow, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (mainwindow, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (mainwindow, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (mainwindow, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (mainwindow, about1, "about1");
  GLADE_HOOKUP_OBJECT (mainwindow, addresscombobox, "addresscombobox");
  GLADE_HOOKUP_OBJECT (mainwindow, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (mainwindow, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (mainwindow, buddy_button, "buddy_button");
  GLADE_HOOKUP_OBJECT (mainwindow, buddy, "buddy");
  GLADE_HOOKUP_OBJECT (mainwindow, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (mainwindow, lastnameentry, "lastnameentry");
  GLADE_HOOKUP_OBJECT (mainwindow, firstnameentry, "firstnameentry");
  GLADE_HOOKUP_OBJECT (mainwindow, label2, "label2");
  GLADE_HOOKUP_OBJECT (mainwindow, streetentry, "streetentry");
  GLADE_HOOKUP_OBJECT (mainwindow, label4, "label4");
  GLADE_HOOKUP_OBJECT (mainwindow, noentry, "noentry");
  GLADE_HOOKUP_OBJECT (mainwindow, label5, "label5");
  GLADE_HOOKUP_OBJECT (mainwindow, zipentry, "zipentry");
  GLADE_HOOKUP_OBJECT (mainwindow, cityentry, "cityentry");
  GLADE_HOOKUP_OBJECT (mainwindow, label7, "label7");
  GLADE_HOOKUP_OBJECT (mainwindow, phoneentry, "phoneentry");
  GLADE_HOOKUP_OBJECT (mainwindow, label8, "label8");
  GLADE_HOOKUP_OBJECT (mainwindow, mobileentry, "mobileentry");
  GLADE_HOOKUP_OBJECT (mainwindow, label9, "label9");
  GLADE_HOOKUP_OBJECT (mainwindow, emailentry, "emailentry");
  GLADE_HOOKUP_OBJECT (mainwindow, label10, "label10");
  GLADE_HOOKUP_OBJECT (mainwindow, emailsend, "emailsend");
  GLADE_HOOKUP_OBJECT (mainwindow, label6, "label6");
  GLADE_HOOKUP_OBJECT (mainwindow, label3, "label3");
  GLADE_HOOKUP_OBJECT (mainwindow, url, "url");
  GLADE_HOOKUP_OBJECT (mainwindow, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (mainwindow, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (mainwindow, newbutton, "newbutton");
  GLADE_HOOKUP_OBJECT (mainwindow, savebutton, "savebutton");
  GLADE_HOOKUP_OBJECT (mainwindow, deletebutton, "deletebutton");
  GLADE_HOOKUP_OBJECT (mainwindow, quitbutton, "quitbutton");
  GLADE_HOOKUP_OBJECT_NO_REF (mainwindow, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (mainwindow), accel_group);

  return mainwindow;
}

GtkWidget*
create_dialog1 (void)
{
  GtkWidget *dialog1;
  GtkWidget *dialog_vbox1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label11;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;

  dialog1 = gtk_dialog_new ();
  gtk_widget_set_size_request (dialog1, 350, 150);
  gtk_window_set_title (GTK_WINDOW (dialog1), "Question");
  gtk_window_set_modal (GTK_WINDOW (dialog1), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (dialog1), FALSE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (dialog1), TRUE);
  gtk_window_set_icon_name (GTK_WINDOW (dialog1), "stock_book_red");
  gtk_window_set_type_hint (GTK_WINDOW (dialog1), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (dialog1)->vbox;
  gtk_widget_show (dialog_vbox1);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), hbox1, TRUE, TRUE, 0);

  image1 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, TRUE, TRUE, 0);

  label11 = gtk_label_new ("Do you really want to delete this contact?");
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox1), label11, FALSE, FALSE, 0);

  dialog_action_area1 = GTK_DIALOG (dialog1)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-no");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), cancelbutton1, GTK_RESPONSE_NO);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-yes");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), okbutton1, GTK_RESPONSE_YES);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog1, "dialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (dialog1, image1, "image1");
  GLADE_HOOKUP_OBJECT (dialog1, label11, "label11");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog1, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (dialog1, okbutton1, "okbutton1");

  return dialog1;
}

GtkWidget*
create_dialog2 (void)
{
  GtkWidget *dialog2;
  GtkWidget *dialog_vbox2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label12;
  GtkWidget *dialog_action_area2;
  GtkWidget *closebutton1;

  dialog2 = gtk_dialog_new ();
  gtk_widget_set_size_request (dialog2, 350, 150);
  gtk_window_set_title (GTK_WINDOW (dialog2), "Information");
  gtk_window_set_icon_name (GTK_WINDOW (dialog2), "stock_book_red");
  gtk_window_set_type_hint (GTK_WINDOW (dialog2), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (dialog2)->vbox;
  gtk_widget_show (dialog_vbox2);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), hbox2, TRUE, TRUE, 0);

  image2 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, TRUE, TRUE, 0);

  label12 = gtk_label_new ("You must enter a last name and first name.");
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox2), label12, FALSE, FALSE, 0);

  dialog_action_area2 = GTK_DIALOG (dialog2)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  closebutton1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog2), closebutton1, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton1, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog2, "dialog2");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dialog2, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (dialog2, image2, "image2");
  GLADE_HOOKUP_OBJECT (dialog2, label12, "label12");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dialog2, closebutton1, "closebutton1");

  return dialog2;
}

GtkWidget*
create_aboutdialog1 (void)
{
  GtkWidget *aboutdialog1;
  const gchar *authors[] = {
    "Isenmann Daniel (daniel.isenmann@gmx.de)",
    NULL
  };

  aboutdialog1 = gtk_about_dialog_new ();
  gtk_window_set_destroy_with_parent (GTK_WINDOW (aboutdialog1), TRUE);
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (aboutdialog1), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (aboutdialog1), "gfa");
  gtk_about_dialog_set_copyright (GTK_ABOUT_DIALOG (aboutdialog1), "(C) 2006 Isenmann Daniel\nLicensed under the GNU General Public License");
  gtk_about_dialog_set_comments (GTK_ABOUT_DIALOG (aboutdialog1), "GTK+ fast address\ngfa is a small and fast address book");
  gtk_about_dialog_set_website (GTK_ABOUT_DIALOG (aboutdialog1), "http://gfa.sourceforge.net");
  gtk_about_dialog_set_authors (GTK_ABOUT_DIALOG (aboutdialog1), authors);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aboutdialog1, aboutdialog1, "aboutdialog1");

  return aboutdialog1;
}

GtkWidget*
create_dialog3 (void)
{
  GtkWidget *dialog3;
  GtkWidget *dialog_vbox3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label13;
  GtkWidget *dialog_action_area3;
  GtkWidget *okbutton2;

  dialog3 = gtk_dialog_new ();
  gtk_widget_set_size_request (dialog3, 350, 150);
  gtk_window_set_title (GTK_WINDOW (dialog3), "Information");
  gtk_window_set_type_hint (GTK_WINDOW (dialog3), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox3 = GTK_DIALOG (dialog3)->vbox;
  gtk_widget_show (dialog_vbox3);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), hbox3, TRUE, TRUE, 0);

  image3 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, TRUE, TRUE, 0);

  label13 = gtk_label_new ("Not implemented at the moment.\nComing soon.");
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox3), label13, FALSE, FALSE, 0);

  dialog_action_area3 = GTK_DIALOG (dialog3)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  okbutton2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog3), okbutton2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton2, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog3, dialog3, "dialog3");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog3, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (dialog3, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (dialog3, image3, "image3");
  GLADE_HOOKUP_OBJECT (dialog3, label13, "label13");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog3, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (dialog3, okbutton2, "okbutton2");

  return dialog3;
}

GtkWidget*
create_filechooserdialog (void)
{
  GtkWidget *filechooserdialog;
  GtkWidget *dialog_vbox4;
  GtkWidget *dialog_action_area4;
  GtkWidget *button2;
  GtkWidget *button3;
  GtkWidget *button4;

  filechooserdialog = gtk_file_chooser_dialog_new ("Choose picture for icon...", NULL, GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_window_set_modal (GTK_WINDOW (filechooserdialog), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (filechooserdialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox4 = GTK_DIALOG (filechooserdialog)->vbox;
  gtk_widget_show (dialog_vbox4);

  dialog_action_area4 = GTK_DIALOG (filechooserdialog)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  button2 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button2);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog), button2, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  button3 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (button3);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog), button3, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);

  button4 = gtk_button_new_with_mnemonic ("Use default icon");
  gtk_widget_show (button4);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog), button4, 123);
  GTK_WIDGET_SET_FLAGS (button4, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog, filechooserdialog, "filechooserdialog");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (filechooserdialog, button2, "button2");
  GLADE_HOOKUP_OBJECT (filechooserdialog, button3, "button3");
  GLADE_HOOKUP_OBJECT (filechooserdialog, button4, "button4");

  gtk_widget_grab_default (button3);
  return filechooserdialog;
}

