/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mainwindow (void)
{
  GtkWidget *mainwindow;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *new1;
  GtkWidget *save1;
  GtkWidget *delete2;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit1;
  GtkWidget *group1;
  GtkWidget *group1_menu;
  GtkWidget *new_group;
  GtkWidget *image14;
  GtkWidget *rename_group;
  GtkWidget *image15;
  GtkWidget *delete_group;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *about1;
  GtkWidget *hbox4;
  GtkWidget *groupcombobox;
  GtkWidget *addresscombobox;
  GtkWidget *hseparator2;
  GtkWidget *hbox1;
  GtkWidget *buddy_button;
  GtkWidget *buddy;
  GtkWidget *fixed1;
  GtkWidget *lastnameentry;
  GtkWidget *firstnameentry;
  GtkWidget *streetentry;
  GtkWidget *label4;
  GtkWidget *noentry;
  GtkWidget *label5;
  GtkWidget *zipentry;
  GtkWidget *cityentry;
  GtkWidget *label7;
  GtkWidget *phoneentry;
  GtkWidget *label8;
  GtkWidget *mobileentry;
  GtkWidget *label9;
  GtkWidget *emailentry;
  GtkWidget *emailsend;
  GtkWidget *url;
  GtkWidget *label6;
  GtkWidget *label10;
  GtkWidget *label3;
  GtkWidget *label2;
  GtkWidget *expander;
  GtkWidget *fixed3;
  GtkWidget *webentry;
  GtkWidget *icqentry;
  GtkWidget *yahooentry;
  GtkWidget *msnentry;
  GtkWidget *birthdateentry;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *datebutton;
  GtkWidget *image4;
  GtkWidget *workphoneentry;
  GtkWidget *workmobileentry;
  GtkWidget *workemailentry;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label17;
  GtkWidget *label26;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *hseparator3;
  GtkWidget *comboboxgroup;
  GtkWidget *label25;
  GtkWidget *hseparator1;
  GtkWidget *hbuttonbox1;
  GtkWidget *newbutton;
  GtkWidget *savebutton;
  GtkWidget *deletebutton;
  GtkWidget *quitbutton;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  mainwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (mainwindow, 611, -1);
  gtk_window_set_title (GTK_WINDOW (mainwindow), "gfa");
  gtk_window_set_resizable (GTK_WINDOW (mainwindow), FALSE);
  gtk_window_set_icon_name (GTK_WINDOW (mainwindow), "stock_book_red");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (mainwindow), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic ("_Contact");
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  new1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (new1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), new1);

  save1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), save1);

  delete2 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_show (delete2);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), delete2);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quit1);

  group1 = gtk_menu_item_new_with_mnemonic ("Group");
  gtk_widget_show (group1);
  gtk_container_add (GTK_CONTAINER (menubar1), group1);

  group1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (group1), group1_menu);

  new_group = gtk_image_menu_item_new_with_mnemonic ("New");
  gtk_widget_show (new_group);
  gtk_container_add (GTK_CONTAINER (group1_menu), new_group);

  image14 = gtk_image_new_from_stock ("gtk-new", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image14);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (new_group), image14);

  rename_group = gtk_image_menu_item_new_with_mnemonic ("Rename");
  gtk_widget_show (rename_group);
  gtk_container_add (GTK_CONTAINER (group1_menu), rename_group);

  image15 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image15);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (rename_group), image15);

  delete_group = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_show (delete_group);
  gtk_container_add (GTK_CONTAINER (group1_menu), delete_group);

  menuitem4 = gtk_menu_item_new_with_mnemonic ("_Help");
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  about1 = gtk_image_menu_item_new_from_stock ("gtk-about", accel_group);
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), about1);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox4, FALSE, TRUE, 0);

  groupcombobox = gtk_combo_box_new_text ();
  gtk_widget_show (groupcombobox);
  gtk_box_pack_start (GTK_BOX (hbox4), groupcombobox, TRUE, TRUE, 0);
  gtk_widget_set_size_request (groupcombobox, 90, -1);
  gtk_container_set_border_width (GTK_CONTAINER (groupcombobox), 3);

  addresscombobox = gtk_combo_box_new_text ();
  gtk_widget_show (addresscombobox);
  gtk_box_pack_start (GTK_BOX (hbox4), addresscombobox, TRUE, TRUE, 0);
  gtk_widget_set_size_request (addresscombobox, 390, -1);
  gtk_container_set_border_width (GTK_CONTAINER (addresscombobox), 3);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator2, FALSE, TRUE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  buddy_button = gtk_button_new ();
  gtk_widget_show (buddy_button);
  gtk_box_pack_start (GTK_BOX (hbox1), buddy_button, FALSE, FALSE, 0);
  gtk_widget_set_size_request (buddy_button, 123, 141);
  gtk_container_set_border_width (GTK_CONTAINER (buddy_button), 3);

  buddy = create_pixmap (mainwindow, "person.png");
  gtk_widget_show (buddy);
  gtk_container_add (GTK_CONTAINER (buddy_button), buddy);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_box_pack_start (GTK_BOX (hbox1), fixed1, TRUE, TRUE, 0);

  lastnameentry = gtk_entry_new ();
  gtk_widget_show (lastnameentry);
  gtk_fixed_put (GTK_FIXED (fixed1), lastnameentry, 80, 16);
  gtk_widget_set_size_request (lastnameentry, 160, 26);

  firstnameentry = gtk_entry_new ();
  gtk_widget_show (firstnameentry);
  gtk_fixed_put (GTK_FIXED (fixed1), firstnameentry, 320, 16);
  gtk_widget_set_size_request (firstnameentry, 160, 26);

  streetentry = gtk_entry_new ();
  gtk_widget_show (streetentry);
  gtk_fixed_put (GTK_FIXED (fixed1), streetentry, 80, 48);
  gtk_widget_set_size_request (streetentry, 288, 26);

  label4 = gtk_label_new ("street:");
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 32, 48);
  gtk_widget_set_size_request (label4, 48, 24);

  noentry = gtk_entry_new ();
  gtk_widget_show (noentry);
  gtk_fixed_put (GTK_FIXED (fixed1), noentry, 408, 48);
  gtk_widget_set_size_request (noentry, 72, 26);

  label5 = gtk_label_new ("no.:");
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 376, 48);
  gtk_widget_set_size_request (label5, 32, 24);

  zipentry = gtk_entry_new ();
  gtk_widget_show (zipentry);
  gtk_fixed_put (GTK_FIXED (fixed1), zipentry, 80, 80);
  gtk_widget_set_size_request (zipentry, 56, 26);

  cityentry = gtk_entry_new ();
  gtk_widget_show (cityentry);
  gtk_fixed_put (GTK_FIXED (fixed1), cityentry, 184, 80);
  gtk_widget_set_size_request (cityentry, 295, 27);

  label7 = gtk_label_new ("city:");
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 144, 80);
  gtk_widget_set_size_request (label7, 40, 24);

  phoneentry = gtk_entry_new ();
  gtk_widget_show (phoneentry);
  gtk_fixed_put (GTK_FIXED (fixed1), phoneentry, 80, 112);
  gtk_widget_set_size_request (phoneentry, 160, 27);

  label8 = gtk_label_new ("phone:");
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 24, 112);
  gtk_widget_set_size_request (label8, 56, 24);

  mobileentry = gtk_entry_new ();
  gtk_widget_show (mobileentry);
  gtk_fixed_put (GTK_FIXED (fixed1), mobileentry, 320, 112);
  gtk_widget_set_size_request (mobileentry, 160, 27);

  label9 = gtk_label_new ("mobile:");
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed1), label9, 264, 112);
  gtk_widget_set_size_request (label9, 56, 24);

  emailentry = gtk_entry_new ();
  gtk_widget_show (emailentry);
  gtk_fixed_put (GTK_FIXED (fixed1), emailentry, 80, 144);
  gtk_widget_set_size_request (emailentry, 332, 27);

  emailsend = gtk_button_new_with_mnemonic ("send");
  gtk_widget_show (emailsend);
  gtk_fixed_put (GTK_FIXED (fixed1), emailsend, 416, 144);
  gtk_widget_set_size_request (emailsend, 64, 27);
  gtk_tooltips_set_tip (tooltips, emailsend, "Send an email to your contact with your mail client.", NULL);

  url = gtk_label_new ("label14");
  gtk_fixed_put (GTK_FIXED (fixed1), url, 88, 24);
  gtk_widget_set_size_request (url, 46, 17);
  gtk_widget_set_sensitive (url, FALSE);

  label6 = gtk_label_new ("zip:");
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 40, 80);
  gtk_widget_set_size_request (label6, 48, 24);

  label10 = gtk_label_new ("email:");
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed1), label10, 32, 144);
  gtk_widget_set_size_request (label10, 48, 24);

  label3 = gtk_label_new ("last name:");
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 8, 16);
  gtk_widget_set_size_request (label3, 72, 24);

  label2 = gtk_label_new ("first name:");
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 240, 16);
  gtk_widget_set_size_request (label2, 88, 24);

  expander = gtk_expander_new (NULL);
  gtk_widget_show (expander);
  gtk_box_pack_start (GTK_BOX (vbox1), expander, TRUE, TRUE, 0);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (expander), fixed3);
  gtk_widget_set_size_request (fixed3, -1, 182);

  webentry = gtk_entry_new ();
  gtk_widget_show (webentry);
  gtk_fixed_put (GTK_FIXED (fixed3), webentry, 80, 48);
  gtk_widget_set_size_request (webentry, 215, 26);

  icqentry = gtk_entry_new ();
  gtk_widget_show (icqentry);
  gtk_fixed_put (GTK_FIXED (fixed3), icqentry, 80, 80);
  gtk_widget_set_size_request (icqentry, 215, 26);

  yahooentry = gtk_entry_new ();
  gtk_widget_show (yahooentry);
  gtk_fixed_put (GTK_FIXED (fixed3), yahooentry, 80, 112);
  gtk_widget_set_size_request (yahooentry, 215, 26);

  msnentry = gtk_entry_new ();
  gtk_widget_show (msnentry);
  gtk_fixed_put (GTK_FIXED (fixed3), msnentry, 80, 144);
  gtk_widget_set_size_request (msnentry, 215, 26);

  birthdateentry = gtk_entry_new ();
  gtk_widget_show (birthdateentry);
  gtk_fixed_put (GTK_FIXED (fixed3), birthdateentry, 80, 16);
  gtk_widget_set_size_request (birthdateentry, 184, 26);

  label18 = gtk_label_new (" icq:");
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 32, 80);
  gtk_widget_set_size_request (label18, 56, 24);

  label19 = gtk_label_new (" yahoo:");
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 22, 112);
  gtk_widget_set_size_request (label19, 56, 24);

  label20 = gtk_label_new (" msn:");
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 28, 144);
  gtk_widget_set_size_request (label20, 56, 24);

  datebutton = gtk_button_new ();
  gtk_widget_show (datebutton);
  gtk_fixed_put (GTK_FIXED (fixed3), datebutton, 264, 16);
  gtk_widget_set_size_request (datebutton, 32, 26);

  image4 = gtk_image_new_from_icon_name ("stock_form-date-field", GTK_ICON_SIZE_BUTTON);
  gtk_image_set_pixel_size (image4, 1);
  gtk_widget_show (image4);
  gtk_container_add (GTK_CONTAINER (datebutton), image4);

  workphoneentry = gtk_entry_new ();
  gtk_widget_show (workphoneentry);
  gtk_fixed_put (GTK_FIXED (fixed3), workphoneentry, 388, 16);
  gtk_widget_set_size_request (workphoneentry, 215, 26);

  workmobileentry = gtk_entry_new ();
  gtk_widget_show (workmobileentry);
  gtk_fixed_put (GTK_FIXED (fixed3), workmobileentry, 388, 48);
  gtk_widget_set_size_request (workmobileentry, 215, 26);

  workemailentry = gtk_entry_new ();
  gtk_widget_show (workemailentry);
  gtk_fixed_put (GTK_FIXED (fixed3), workemailentry, 388, 80);
  gtk_widget_set_size_request (workemailentry, 215, 26);

  label27 = gtk_label_new (" work phone:");
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed3), label27, 294, 16);
  gtk_widget_set_size_request (label27, 96, 24);

  label28 = gtk_label_new (" work mobile:");
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed3), label28, 294, 48);
  gtk_widget_set_size_request (label28, 96, 24);

  label17 = gtk_label_new (" web:");
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 37, 40);
  gtk_widget_set_size_request (label17, 39, 38);

  label26 = gtk_label_new (" birthday:");
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed3), label26, 8, 16);
  gtk_widget_set_size_request (label26, 72, 24);

  label29 = gtk_label_new (" work email:");
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed3), label29, 302, 80);
  gtk_widget_set_size_request (label29, 88, 24);

  label30 = gtk_label_new ("group: ");
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed3), label30, 339, 112);
  gtk_widget_set_size_request (label30, 56, 32);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_fixed_put (GTK_FIXED (fixed3), hseparator3, 8, 0);
  gtk_widget_set_size_request (hseparator3, 592, 16);

  comboboxgroup = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxgroup);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxgroup, 388, 112);
  gtk_widget_set_size_request (comboboxgroup, 215, 32);

  label25 = gtk_label_new ("more fields");
  gtk_widget_show (label25);
  gtk_expander_set_label_widget (GTK_EXPANDER (expander), label25);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator1, FALSE, TRUE, 0);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbuttonbox1, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox1), 3);

  newbutton = gtk_button_new_from_stock ("gtk-new");
  gtk_widget_show (newbutton);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), newbutton);
  GTK_WIDGET_SET_FLAGS (newbutton, GTK_CAN_DEFAULT);

  savebutton = gtk_button_new_from_stock ("gtk-save");
  gtk_widget_show (savebutton);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), savebutton);
  GTK_WIDGET_SET_FLAGS (savebutton, GTK_CAN_DEFAULT);

  deletebutton = gtk_button_new_from_stock ("gtk-delete");
  gtk_widget_show (deletebutton);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), deletebutton);
  GTK_WIDGET_SET_FLAGS (deletebutton, GTK_CAN_DEFAULT);

  quitbutton = gtk_button_new_from_stock ("gtk-quit");
  gtk_widget_show (quitbutton);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), quitbutton);
  GTK_WIDGET_SET_FLAGS (quitbutton, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) mainwindow, "delete_event",
                    G_CALLBACK (on_mainwindow_delete_event),
                    NULL);
  g_signal_connect ((gpointer) mainwindow, "realize",
                    G_CALLBACK (on_mainwindow_realize),
                    NULL);
  g_signal_connect ((gpointer) new1, "activate",
                    G_CALLBACK (on_new_activate),
                    NULL);
  g_signal_connect ((gpointer) save1, "activate",
                    G_CALLBACK (on_save_activate),
                    NULL);
  g_signal_connect ((gpointer) delete2, "activate",
                    G_CALLBACK (on_delete_activate),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit_activate),
                    NULL);
  g_signal_connect ((gpointer) group1, "activate",
                    G_CALLBACK (on_group1_activate),
                    NULL);
  g_signal_connect ((gpointer) new_group, "activate",
                    G_CALLBACK (on_new_group_activate),
                    NULL);
  g_signal_connect ((gpointer) rename_group, "activate",
                    G_CALLBACK (on_rename_group_activate),
                    NULL);
  g_signal_connect ((gpointer) delete_group, "activate",
                    G_CALLBACK (on_delete_group_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about_activate),
                    NULL);
  g_signal_connect ((gpointer) groupcombobox, "changed",
                    G_CALLBACK (on_groupcombobox_changed),
                    NULL);
  g_signal_connect ((gpointer) addresscombobox, "changed",
                    G_CALLBACK (on_addresscombobox_changed),
                    NULL);
  g_signal_connect ((gpointer) buddy_button, "clicked",
                    G_CALLBACK (on_buddy_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) emailsend, "clicked",
                    G_CALLBACK (on_emailsend_clicked),
                    NULL);
  g_signal_connect ((gpointer) expander, "notify::expanded",
                    G_CALLBACK (expander_callback),
                    NULL);
  g_signal_connect ((gpointer) datebutton, "clicked",
                    G_CALLBACK (on_datebutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) newbutton, "clicked",
                    G_CALLBACK (on_newbutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) savebutton, "clicked",
                    G_CALLBACK (on_savebutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) deletebutton, "clicked",
                    G_CALLBACK (on_deletebutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) quitbutton, "clicked",
                    G_CALLBACK (on_quitbutton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mainwindow, mainwindow, "mainwindow");
  GLADE_HOOKUP_OBJECT (mainwindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (mainwindow, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (mainwindow, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (mainwindow, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (mainwindow, new1, "new1");
  GLADE_HOOKUP_OBJECT (mainwindow, save1, "save1");
  GLADE_HOOKUP_OBJECT (mainwindow, delete2, "delete2");
  GLADE_HOOKUP_OBJECT (mainwindow, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (mainwindow, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (mainwindow, group1, "group1");
  GLADE_HOOKUP_OBJECT (mainwindow, group1_menu, "group1_menu");
  GLADE_HOOKUP_OBJECT (mainwindow, new_group, "new_group");
  GLADE_HOOKUP_OBJECT (mainwindow, image14, "image14");
  GLADE_HOOKUP_OBJECT (mainwindow, rename_group, "rename_group");
  GLADE_HOOKUP_OBJECT (mainwindow, image15, "image15");
  GLADE_HOOKUP_OBJECT (mainwindow, delete_group, "delete_group");
  GLADE_HOOKUP_OBJECT (mainwindow, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (mainwindow, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (mainwindow, about1, "about1");
  GLADE_HOOKUP_OBJECT (mainwindow, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (mainwindow, groupcombobox, "groupcombobox");
  GLADE_HOOKUP_OBJECT (mainwindow, addresscombobox, "addresscombobox");
  GLADE_HOOKUP_OBJECT (mainwindow, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (mainwindow, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (mainwindow, buddy_button, "buddy_button");
  GLADE_HOOKUP_OBJECT (mainwindow, buddy, "buddy");
  GLADE_HOOKUP_OBJECT (mainwindow, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (mainwindow, lastnameentry, "lastnameentry");
  GLADE_HOOKUP_OBJECT (mainwindow, firstnameentry, "firstnameentry");
  GLADE_HOOKUP_OBJECT (mainwindow, streetentry, "streetentry");
  GLADE_HOOKUP_OBJECT (mainwindow, label4, "label4");
  GLADE_HOOKUP_OBJECT (mainwindow, noentry, "noentry");
  GLADE_HOOKUP_OBJECT (mainwindow, label5, "label5");
  GLADE_HOOKUP_OBJECT (mainwindow, zipentry, "zipentry");
  GLADE_HOOKUP_OBJECT (mainwindow, cityentry, "cityentry");
  GLADE_HOOKUP_OBJECT (mainwindow, label7, "label7");
  GLADE_HOOKUP_OBJECT (mainwindow, phoneentry, "phoneentry");
  GLADE_HOOKUP_OBJECT (mainwindow, label8, "label8");
  GLADE_HOOKUP_OBJECT (mainwindow, mobileentry, "mobileentry");
  GLADE_HOOKUP_OBJECT (mainwindow, label9, "label9");
  GLADE_HOOKUP_OBJECT (mainwindow, emailentry, "emailentry");
  GLADE_HOOKUP_OBJECT (mainwindow, emailsend, "emailsend");
  GLADE_HOOKUP_OBJECT (mainwindow, url, "url");
  GLADE_HOOKUP_OBJECT (mainwindow, label6, "label6");
  GLADE_HOOKUP_OBJECT (mainwindow, label10, "label10");
  GLADE_HOOKUP_OBJECT (mainwindow, label3, "label3");
  GLADE_HOOKUP_OBJECT (mainwindow, label2, "label2");
  GLADE_HOOKUP_OBJECT (mainwindow, expander, "expander");
  GLADE_HOOKUP_OBJECT (mainwindow, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (mainwindow, webentry, "webentry");
  GLADE_HOOKUP_OBJECT (mainwindow, icqentry, "icqentry");
  GLADE_HOOKUP_OBJECT (mainwindow, yahooentry, "yahooentry");
  GLADE_HOOKUP_OBJECT (mainwindow, msnentry, "msnentry");
  GLADE_HOOKUP_OBJECT (mainwindow, birthdateentry, "birthdateentry");
  GLADE_HOOKUP_OBJECT (mainwindow, label18, "label18");
  GLADE_HOOKUP_OBJECT (mainwindow, label19, "label19");
  GLADE_HOOKUP_OBJECT (mainwindow, label20, "label20");
  GLADE_HOOKUP_OBJECT (mainwindow, datebutton, "datebutton");
  GLADE_HOOKUP_OBJECT (mainwindow, image4, "image4");
  GLADE_HOOKUP_OBJECT (mainwindow, workphoneentry, "workphoneentry");
  GLADE_HOOKUP_OBJECT (mainwindow, workmobileentry, "workmobileentry");
  GLADE_HOOKUP_OBJECT (mainwindow, workemailentry, "workemailentry");
  GLADE_HOOKUP_OBJECT (mainwindow, label27, "label27");
  GLADE_HOOKUP_OBJECT (mainwindow, label28, "label28");
  GLADE_HOOKUP_OBJECT (mainwindow, label17, "label17");
  GLADE_HOOKUP_OBJECT (mainwindow, label26, "label26");
  GLADE_HOOKUP_OBJECT (mainwindow, label29, "label29");
  GLADE_HOOKUP_OBJECT (mainwindow, label30, "label30");
  GLADE_HOOKUP_OBJECT (mainwindow, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (mainwindow, comboboxgroup, "comboboxgroup");
  GLADE_HOOKUP_OBJECT (mainwindow, label25, "label25");
  GLADE_HOOKUP_OBJECT (mainwindow, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (mainwindow, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (mainwindow, newbutton, "newbutton");
  GLADE_HOOKUP_OBJECT (mainwindow, savebutton, "savebutton");
  GLADE_HOOKUP_OBJECT (mainwindow, deletebutton, "deletebutton");
  GLADE_HOOKUP_OBJECT (mainwindow, quitbutton, "quitbutton");
  GLADE_HOOKUP_OBJECT_NO_REF (mainwindow, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (mainwindow), accel_group);

  return mainwindow;
}

GtkWidget*
create_dialog1 (void)
{
  GtkWidget *dialog1;
  GtkWidget *dialog_vbox1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label11;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;

  dialog1 = gtk_dialog_new ();
  gtk_widget_set_size_request (dialog1, 350, 150);
  gtk_window_set_title (GTK_WINDOW (dialog1), "Question");
  gtk_window_set_position (GTK_WINDOW (dialog1), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (dialog1), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (dialog1), FALSE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (dialog1), TRUE);
  gtk_window_set_icon_name (GTK_WINDOW (dialog1), "stock_book_red");
  gtk_window_set_type_hint (GTK_WINDOW (dialog1), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (dialog1)->vbox;
  gtk_widget_show (dialog_vbox1);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), hbox1, TRUE, TRUE, 0);

  image1 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, TRUE, TRUE, 0);

  label11 = gtk_label_new ("Do you really want to delete this contact?");
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox1), label11, FALSE, FALSE, 0);

  dialog_action_area1 = GTK_DIALOG (dialog1)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-no");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), cancelbutton1, GTK_RESPONSE_NO);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-yes");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), okbutton1, GTK_RESPONSE_YES);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog1, "dialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (dialog1, image1, "image1");
  GLADE_HOOKUP_OBJECT (dialog1, label11, "label11");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog1, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (dialog1, okbutton1, "okbutton1");

  return dialog1;
}

GtkWidget*
create_dialog2 (void)
{
  GtkWidget *dialog2;
  GtkWidget *dialog_vbox2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label12;
  GtkWidget *dialog_action_area2;
  GtkWidget *closebutton1;

  dialog2 = gtk_dialog_new ();
  gtk_widget_set_size_request (dialog2, 350, 150);
  gtk_window_set_title (GTK_WINDOW (dialog2), "Information");
  gtk_window_set_position (GTK_WINDOW (dialog2), GTK_WIN_POS_MOUSE);
  gtk_window_set_icon_name (GTK_WINDOW (dialog2), "stock_book_red");
  gtk_window_set_type_hint (GTK_WINDOW (dialog2), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (dialog2)->vbox;
  gtk_widget_show (dialog_vbox2);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), hbox2, TRUE, TRUE, 0);

  image2 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, TRUE, TRUE, 0);

  label12 = gtk_label_new ("You must enter a last name and first name.");
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox2), label12, FALSE, FALSE, 0);

  dialog_action_area2 = GTK_DIALOG (dialog2)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  closebutton1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog2), closebutton1, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton1, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog2, "dialog2");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dialog2, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (dialog2, image2, "image2");
  GLADE_HOOKUP_OBJECT (dialog2, label12, "label12");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dialog2, closebutton1, "closebutton1");

  return dialog2;
}

GtkWidget*
create_aboutdialog1 (void)
{
  GtkWidget *aboutdialog1;
  const gchar *authors[] = {
    "Isenmann Daniel (daniel.isenmann@gmx.de)",
    NULL
  };

  aboutdialog1 = gtk_about_dialog_new ();
  gtk_window_set_destroy_with_parent (GTK_WINDOW (aboutdialog1), TRUE);
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (aboutdialog1), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (aboutdialog1), "gfa");
  gtk_about_dialog_set_copyright (GTK_ABOUT_DIALOG (aboutdialog1), "(C) 2006 Isenmann Daniel\nLicensed under the GNU General Public License");
  gtk_about_dialog_set_comments (GTK_ABOUT_DIALOG (aboutdialog1), "GTK+ fast address\ngfa is a small and fast address book");
  gtk_about_dialog_set_website (GTK_ABOUT_DIALOG (aboutdialog1), "http://gfa.sourceforge.net");
  gtk_about_dialog_set_authors (GTK_ABOUT_DIALOG (aboutdialog1), authors);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aboutdialog1, aboutdialog1, "aboutdialog1");

  return aboutdialog1;
}

GtkWidget*
create_dialog3 (void)
{
  GtkWidget *dialog3;
  GtkWidget *dialog_vbox3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label13;
  GtkWidget *dialog_action_area3;
  GtkWidget *okbutton2;

  dialog3 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog3), "Information");
  gtk_window_set_position (GTK_WINDOW (dialog3), GTK_WIN_POS_MOUSE);
  gtk_window_set_type_hint (GTK_WINDOW (dialog3), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox3 = GTK_DIALOG (dialog3)->vbox;
  gtk_widget_show (dialog_vbox3);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), hbox3, TRUE, TRUE, 0);

  image3 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, TRUE, TRUE, 0);

  label13 = gtk_label_new ("Not implemented at the moment.\nComing soon.");
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox3), label13, FALSE, FALSE, 0);

  dialog_action_area3 = GTK_DIALOG (dialog3)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  okbutton2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog3), okbutton2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton2, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog3, dialog3, "dialog3");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog3, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (dialog3, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (dialog3, image3, "image3");
  GLADE_HOOKUP_OBJECT (dialog3, label13, "label13");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog3, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (dialog3, okbutton2, "okbutton2");

  return dialog3;
}

GtkWidget*
create_filechooserdialog (void)
{
  GtkWidget *filechooserdialog;
  GtkWidget *dialog_vbox4;
  GtkWidget *dialog_action_area4;
  GtkWidget *button2;
  GtkWidget *button3;
  GtkWidget *button4;

  filechooserdialog = gtk_file_chooser_dialog_new ("Choose picture for icon...", NULL, GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_window_set_modal (GTK_WINDOW (filechooserdialog), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (filechooserdialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox4 = GTK_DIALOG (filechooserdialog)->vbox;
  gtk_widget_show (dialog_vbox4);

  dialog_action_area4 = GTK_DIALOG (filechooserdialog)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  button2 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button2);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog), button2, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  button3 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (button3);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog), button3, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);

  button4 = gtk_button_new_with_mnemonic ("Use default icon");
  gtk_widget_show (button4);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog), button4, 123);
  GTK_WIDGET_SET_FLAGS (button4, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog, filechooserdialog, "filechooserdialog");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (filechooserdialog, button2, "button2");
  GLADE_HOOKUP_OBJECT (filechooserdialog, button3, "button3");
  GLADE_HOOKUP_OBJECT (filechooserdialog, button4, "button4");

  gtk_widget_grab_default (button3);
  return filechooserdialog;
}

GtkWidget*
create_caldialog (void)
{
  GtkWidget *caldialog;
  GtkWidget *dialog_vbox5;
  GtkWidget *calendar;
  GtkWidget *dialog_action_area5;

  caldialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (caldialog), "Double-click on date to choose");
  gtk_window_set_position (GTK_WINDOW (caldialog), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (caldialog), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (caldialog), FALSE);
  gtk_window_set_icon_name (GTK_WINDOW (caldialog), "stock_book_red");
  gtk_window_set_decorated (GTK_WINDOW (caldialog), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (caldialog), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_window_set_gravity (GTK_WINDOW (caldialog), GDK_GRAVITY_CENTER);

  dialog_vbox5 = GTK_DIALOG (caldialog)->vbox;
  gtk_widget_show (dialog_vbox5);

  calendar = gtk_calendar_new ();
  gtk_widget_show (calendar);
  gtk_box_pack_start (GTK_BOX (dialog_vbox5), calendar, TRUE, TRUE, 0);
  gtk_calendar_display_options (GTK_CALENDAR (calendar),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES
                                | GTK_CALENDAR_SHOW_WEEK_NUMBERS);

  dialog_action_area5 = GTK_DIALOG (caldialog)->action_area;
  gtk_widget_show (dialog_action_area5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area5), GTK_BUTTONBOX_END);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (caldialog, caldialog, "caldialog");
  GLADE_HOOKUP_OBJECT_NO_REF (caldialog, dialog_vbox5, "dialog_vbox5");
  GLADE_HOOKUP_OBJECT (caldialog, calendar, "calendar");
  GLADE_HOOKUP_OBJECT_NO_REF (caldialog, dialog_action_area5, "dialog_action_area5");

  return caldialog;
}

GtkWidget*
create_dialog4 (void)
{
  GtkWidget *dialog4;
  GtkWidget *dialog_vbox6;
  GtkWidget *vbox2;
  GtkWidget *label31;
  GtkWidget *groupentry;
  GtkWidget *dialog_action_area6;
  GtkWidget *cancelbutton2;
  GtkWidget *okbutton3;
  GtkWidget *alignment2;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label34;

  dialog4 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog4), "New group...");
  gtk_window_set_position (GTK_WINDOW (dialog4), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (dialog4), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (dialog4), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox6 = GTK_DIALOG (dialog4)->vbox;
  gtk_widget_show (dialog_vbox6);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox6), vbox2, TRUE, TRUE, 0);

  label31 = gtk_label_new ("\nEnter a name for the new group:");
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (vbox2), label31, FALSE, FALSE, 0);

  groupentry = gtk_entry_new ();
  gtk_widget_show (groupentry);
  gtk_box_pack_start (GTK_BOX (vbox2), groupentry, FALSE, FALSE, 0);
  gtk_entry_set_activates_default (GTK_ENTRY (groupentry), TRUE);

  dialog_action_area6 = GTK_DIALOG (dialog4)->action_area;
  gtk_widget_show (dialog_action_area6);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area6), GTK_BUTTONBOX_END);

  cancelbutton2 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog4), cancelbutton2, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton2, GTK_CAN_DEFAULT);

  okbutton3 = gtk_button_new ();
  gtk_widget_show (okbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog4), okbutton3, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton3, GTK_CAN_DEFAULT);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (okbutton3), alignment2);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic ("Create");
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox6), label34, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog4, dialog4, "dialog4");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog4, dialog_vbox6, "dialog_vbox6");
  GLADE_HOOKUP_OBJECT (dialog4, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (dialog4, label31, "label31");
  GLADE_HOOKUP_OBJECT (dialog4, groupentry, "groupentry");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog4, dialog_action_area6, "dialog_action_area6");
  GLADE_HOOKUP_OBJECT (dialog4, cancelbutton2, "cancelbutton2");
  GLADE_HOOKUP_OBJECT (dialog4, okbutton3, "okbutton3");
  GLADE_HOOKUP_OBJECT (dialog4, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (dialog4, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (dialog4, image6, "image6");
  GLADE_HOOKUP_OBJECT (dialog4, label34, "label34");

  gtk_widget_grab_focus (groupentry);
  gtk_widget_grab_default (okbutton3);
  return dialog4;
}

GtkWidget*
create_dialog5 (void)
{
  GtkWidget *dialog5;
  GtkWidget *vbox3;
  GtkWidget *vbox4;
  GtkWidget *label32;
  GtkWidget *entry1;
  GtkWidget *hbuttonbox2;
  GtkWidget *button5;
  GtkWidget *button6;
  GtkWidget *alignment1;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label33;

  dialog5 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog5), "Rename group...");
  gtk_window_set_position (GTK_WINDOW (dialog5), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (dialog5), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (dialog5), GDK_WINDOW_TYPE_HINT_DIALOG);

  vbox3 = GTK_DIALOG (dialog5)->vbox;
  gtk_widget_show (vbox3);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (vbox3), vbox4, TRUE, TRUE, 0);

  label32 = gtk_label_new ("\nEnter a new name for the group:");
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (vbox4), label32, FALSE, FALSE, 0);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (vbox4), entry1, FALSE, FALSE, 0);
  gtk_entry_set_activates_default (GTK_ENTRY (entry1), TRUE);

  hbuttonbox2 = GTK_DIALOG (dialog5)->action_area;
  gtk_widget_show (hbuttonbox2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_END);

  button5 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button5);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog5), button5, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button5, GTK_CAN_DEFAULT);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog5), button6, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button6, GTK_CAN_DEFAULT);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button6), alignment1);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic ("Rename");
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox5), label33, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog5, dialog5, "dialog5");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog5, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (dialog5, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (dialog5, label32, "label32");
  GLADE_HOOKUP_OBJECT (dialog5, entry1, "entry1");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog5, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (dialog5, button5, "button5");
  GLADE_HOOKUP_OBJECT (dialog5, button6, "button6");
  GLADE_HOOKUP_OBJECT (dialog5, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (dialog5, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (dialog5, image5, "image5");
  GLADE_HOOKUP_OBJECT (dialog5, label33, "label33");

  gtk_widget_grab_focus (entry1);
  gtk_widget_grab_default (button6);
  return dialog5;
}

GtkWidget*
create_dialog6 (void)
{
  GtkWidget *dialog6;
  GtkWidget *vbox5;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label35;
  GtkWidget *hbuttonbox3;
  GtkWidget *button7;

  dialog6 = gtk_dialog_new ();
  gtk_widget_set_size_request (dialog6, 350, -1);
  gtk_window_set_title (GTK_WINDOW (dialog6), "Information");
  gtk_window_set_position (GTK_WINDOW (dialog6), GTK_WIN_POS_MOUSE);
  gtk_window_set_type_hint (GTK_WINDOW (dialog6), GDK_WINDOW_TYPE_HINT_DIALOG);

  vbox5 = GTK_DIALOG (dialog6)->vbox;
  gtk_widget_show (vbox5);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox7, TRUE, TRUE, 0);

  image7 = gtk_image_new_from_stock ("gtk-dialog-error", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, TRUE, TRUE, 0);

  label35 = gtk_label_new ("You can't change the name of this group. ");
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox7), label35, FALSE, FALSE, 0);

  hbuttonbox3 = GTK_DIALOG (dialog6)->action_area;
  gtk_widget_show (hbuttonbox3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_END);

  button7 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button7);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog6), button7, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button7, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog6, dialog6, "dialog6");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog6, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (dialog6, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (dialog6, image7, "image7");
  GLADE_HOOKUP_OBJECT (dialog6, label35, "label35");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog6, hbuttonbox3, "hbuttonbox3");
  GLADE_HOOKUP_OBJECT (dialog6, button7, "button7");

  return dialog6;
}

GtkWidget*
create_dialog7 (void)
{
  GtkWidget *dialog7;
  GtkWidget *vbox6;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label36;
  GtkWidget *hbuttonbox4;
  GtkWidget *button8;

  dialog7 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog7), "Information");
  gtk_window_set_position (GTK_WINDOW (dialog7), GTK_WIN_POS_MOUSE);
  gtk_window_set_type_hint (GTK_WINDOW (dialog7), GDK_WINDOW_TYPE_HINT_DIALOG);

  vbox6 = GTK_DIALOG (dialog7)->vbox;
  gtk_widget_show (vbox6);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox8, TRUE, TRUE, 0);

  image8 = gtk_image_new_from_stock ("gtk-dialog-error", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, TRUE, TRUE, 0);

  label36 = gtk_label_new ("You can't delete this group. ");
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox8), label36, FALSE, FALSE, 0);

  hbuttonbox4 = GTK_DIALOG (dialog7)->action_area;
  gtk_widget_show (hbuttonbox4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox4), GTK_BUTTONBOX_END);

  button8 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button8);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog7), button8, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button8, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog7, dialog7, "dialog7");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog7, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (dialog7, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (dialog7, image8, "image8");
  GLADE_HOOKUP_OBJECT (dialog7, label36, "label36");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog7, hbuttonbox4, "hbuttonbox4");
  GLADE_HOOKUP_OBJECT (dialog7, button8, "button8");

  return dialog7;
}

GtkWidget*
create_dialog8 (void)
{
  GtkWidget *dialog8;
  GtkWidget *dialog_vbox7;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label39;
  GtkWidget *dialog_action_area7;
  GtkWidget *button9;
  GtkWidget *alignment3;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label37;
  GtkWidget *button10;
  GtkWidget *alignment4;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label38;
  GtkWidget *button11;

  dialog8 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog8), "Delete or move all contacts in this group?");
  gtk_window_set_position (GTK_WINDOW (dialog8), GTK_WIN_POS_MOUSE);
  gtk_window_set_type_hint (GTK_WINDOW (dialog8), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox7 = GTK_DIALOG (dialog8)->vbox;
  gtk_widget_show (dialog_vbox7);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (dialog_vbox7), hbox11, FALSE, FALSE, 0);

  image11 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, TRUE, TRUE, 0);

  label39 = gtk_label_new ("Do you want to delete the group and all contacts in it or \nmove all contacts from this group to 'General'?         ");
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox11), label39, FALSE, FALSE, 0);

  dialog_action_area7 = GTK_DIALOG (dialog8)->action_area;
  gtk_widget_show (dialog_action_area7);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area7), GTK_BUTTONBOX_END);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog8), button9, 1);
  GTK_WIDGET_SET_FLAGS (button9, GTK_CAN_DEFAULT);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button9), alignment3);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic ("Delete all contacts");
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox9), label37, FALSE, FALSE, 0);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog8), button10, 0);
  GTK_WIDGET_SET_FLAGS (button10, GTK_CAN_DEFAULT);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button10), alignment4);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic ("Move all contacts");
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox10), label38, FALSE, FALSE, 0);

  button11 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button11);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog8), button11, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button11, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog8, dialog8, "dialog8");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog8, dialog_vbox7, "dialog_vbox7");
  GLADE_HOOKUP_OBJECT (dialog8, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (dialog8, image11, "image11");
  GLADE_HOOKUP_OBJECT (dialog8, label39, "label39");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog8, dialog_action_area7, "dialog_action_area7");
  GLADE_HOOKUP_OBJECT (dialog8, button9, "button9");
  GLADE_HOOKUP_OBJECT (dialog8, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (dialog8, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (dialog8, image9, "image9");
  GLADE_HOOKUP_OBJECT (dialog8, label37, "label37");
  GLADE_HOOKUP_OBJECT (dialog8, button10, "button10");
  GLADE_HOOKUP_OBJECT (dialog8, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (dialog8, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (dialog8, image10, "image10");
  GLADE_HOOKUP_OBJECT (dialog8, label38, "label38");
  GLADE_HOOKUP_OBJECT (dialog8, button11, "button11");

  gtk_widget_grab_focus (button11);
  gtk_widget_grab_default (button11);
  return dialog8;
}

